ckeditorapp/urls.py
from django.urls import path, include
from . import views

app_name = 'ckeditorapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail<int:post_id>', views.detail, name='detail'),
    path('add_form', views.add_form, name='add_form'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ckeditorapp.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

"""開発環境課のみ設定"""
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ckeditorapp/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField


class Post(models.Model):
    title = models.CharField('タイトル', max_length=50)
    text = RichTextUploadingField('本文')
    created_at = models.DateField('作成日', auto_now_add=True)
    updated_at = models.DateField('更新日', auto_now=True)

    def __str__(self):
        return self.title

ckeditorapp/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text')
        widgets = {
            'text': CKEditorWidget(),
        }

ckeditorapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Post
from .forms import PostForm
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView, ListView


def index(request):
    post = Post.objects.order_by('-id')
    return render(request, 'ckeditorapp/index.html', {'post': post})


def detail(request, post_id):
    post_text = get_object_or_404(Post, id=post_id)
    return render(request, 'ckeditorapp/detail.html', {'post_text': post_text})


def add_form(request):
    if request.method == 'POST':
        form = PostForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('ckeditorapp:index')

    else:
        form = PostForm

    return render(request, 'ckeditorapp/form.html', {'form': form})

ckeditorapp/templates/ckeditorapp/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <!-- Bootstrap core CSS -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">
  <!-- highlight.js-->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.16.2/build/styles/default.min.css">
  <style>
  </style>
</head>

<body>
  <h1>Blog</h1>

  {% block content %}

  {% endblock content %}

  <script src="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.16.2/build/highlight.min.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>
  <!-- JQuery -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/js/mdb.min.js"></script>
</body>

</html>

ckeditorapp/templates/ckeditorapp/detail.html
{% extends 'ckeditorapp/base.html' %}


{% block content %}
<h1>{{post_text.title}}</h1>
<p>{{post_text.updated_at}}</p>
{{post_text.text | safe}}
<br>

<a href="{% url 'ckeditorapp:index' %}">トップページに戻る</a>
{% endblock content %}

ckeditorapp/templates/ckeditorapp/form.html
{% extends 'ckeditorapp/base.html' %}


{% block content %}
<a href="{%url 'ckeditorapp:index'%}">トップページに戻る</a>

<form action="{% url 'ckeditorapp:add_form' %}" method="POST">
  {% csrf_token %}
  {{form.media}}
  {{form.as_p}}
  <button type="submit">投稿</button>
</form>

{% endblock content %}

ckeditorapp/templates/ckeditorapp/index.html
{% extends 'ckeditorapp/base.html' %}


{% block content %}
<h1>一覧</h1>
<br>

<a href="{% url 'ckeditorapp:add_form' %}">追加&lt;</a>

{% for post in post %}
<ul>
  <li>
    {{post.created_at}}
    {{post.title}}
    <a href="{% url 'ckeditorapp:detail' post_id=post.id %}">詳細</a>
  </li>
</ul>
{% endfor %}

{% endblock content %}